[package]
name = "notcc"
description = "A compiler for a subset of C written in Rust. Based on the book \"Writing a C Compiler\" by Nora Sandler."
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.44", features = ["derive"] }

[[bin]]
name = "notcc"
path = "rust_src/main.rs"

[lib]
name = "notcc"
path = "rust_src/lib.rs"
