import { test, expect } from "vitest";
import * as tacky from "./tacky";
test("Tacky construction", () => {
  const var0 = tacky.Var("tmp0");
  const var1 = tacky.Var("tmp1");
  const c0 = tacky.Constant(37);
  const comp = tacky.Complement(c0, var0);
  const uminus = tacky.UnaryMinus(c0, var1);
  const ret = tacky.Return(var1);
  const func = tacky.Function("main", [comp, uminus, ret]);
  const prog = tacky.Program(func);
  const divOp = tacky.BinaryOp("divide", c0, var0, var1);
  const plusOp = tacky.BinaryOp("plus", c0, var0, var1);
  const minusOp = tacky.BinaryOp("subtract", c0, var0, var1);
  const timesOp = tacky.BinaryOp("multiply", c0, var0, var1);
  const remainderOp = tacky.BinaryOp("remainder", c0, var0, var1);
  expect(prog.func).toBe(func);
  expect(func.name).toBe("main");
  expect(func.body).toHaveLength(3);
  expect(func.body).toEqual([comp, uminus, ret]);
  expect(ret.src).toBe(var1);
  expect(uminus.dst).toBe(var1);
  expect(uminus.src).toBe(c0);
  expect(comp.src).toBe(c0);
  expect(comp.dst).toBe(var0);
  expect(c0.val).toEqual(37);
  expect(var1.name).toBe("tmp1");
  expect(var0.name).toBe("tmp0");
  expect(divOp.kind).toBe("binary-expr");
  expect(divOp.operator).toBe("divide");
  expect(divOp.lhs).toBe(c0);
  expect(divOp.rhs).toBe(var0);
  expect(divOp.dst).toBe(var1);
  expect(plusOp.kind).toBe("binary-expr");
  expect(plusOp.operator).toBe("plus");
  expect(plusOp.lhs).toBe(c0);
  expect(plusOp.rhs).toBe(var0);
  expect(plusOp.dst).toBe(var1);
  expect(minusOp.kind).toBe("binary-expr");
  expect(minusOp.operator).toBe("subtract");
  expect(minusOp.lhs).toBe(c0);
  expect(minusOp.rhs).toBe(var0);
  expect(minusOp.dst).toBe(var1);
  expect(timesOp.kind).toBe("binary-expr");
  expect(timesOp.operator).toBe("multiply");
  expect(timesOp.lhs).toBe(c0);
  expect(timesOp.rhs).toBe(var0);
  expect(timesOp.dst).toBe(var1);
  expect(remainderOp.kind).toBe("binary-expr");
  expect(remainderOp.operator).toBe("remainder");
  expect(remainderOp.lhs).toBe(c0);
  expect(remainderOp.rhs).toBe(var0);
  expect(remainderOp.dst).toBe(var1);
});
